### ISSUE TITLE
Simplify, remove duplication, officialy supported repo

### ISSUE THREAD

**Issue by gblazex** [homerjam/smoothscroll#1]
Hey James!

Author of the original library and gist here.

I migrated the code to an official github repo with bower support.

bower: smoothscroll-for-websites
https://github.com/galambalazs/smoothscroll-for-websites

I believe it's best if you unregister this fork and we converge to a single repo which is always up-to-date.

If you have ideas feel free to submit issues or PRs.

Cheers,
Balázs

**Comment by homerjam** [comment]
Hi Balázs,

Great! I only made this fork to make my life easier really. I have a few projects using it - once I have updated them I will unregister in bower. For now I have added a DEPRECATED warning in the repo.

Thanks,
James

**Comment by gblazex** [comment]
cool :)
